development:
   adapter: postgresql
   database: team_mgmt_dev
   username: avi
   password: avi@singh
   host: localhost

test:
   adapter: postgresql
   database: team_mgmt_test
   username: avi
   password: avi@singh
   host: localhost

production:
   adapter: postgresql
   database: team_mgmt_prod
   username: postgres
   password: postgres
   host: localhost
